package com.xidao.poker.application.account;

public enum AccountErrorCode {
    INVALID_CREDENTIALS,
    GAME_ID_TAKEN,
    INSUFFICIENT_CHIPS,
    ALREADY_AT_TABLE,
    INVALID_EXCHANGE,
    INVALID_REDEMPTION_CODE,
    REDEMPTION_ALREADY_USED,
    REDEMPTION_UNAVAILABLE,
    TABLE_RESULT_NOT_FOUND,
    FORBIDDEN,
    MAIL_NOT_FOUND,
    INVALID_MAIL,
    COSMETIC_NOT_FOUND,
    COSMETIC_ALREADY_OWNED,
    INSUFFICIENT_CRYSTALS,
    INVALID_COSMETIC,
    STORE_REQUEST_CONFLICT,
    UNAUTHORIZED
}
